---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  vagrantfile_erb: .kitchen.Vagrantfile.erb
  plugins:
    cachier:
      cache:
        scope: ":box"
        auto_detect: false
        enable:
          - yum
        generic_buckets:
          - ['chef', '/var/chef/cache']
  network:
  # Kibana
  - ["forwarded_port", {guest: 5601, host: 8081}]
  # ElasticSearch
  - ["forwarded_port", {guest: 9200, host: 9200}]
  customize:
    memory: 1024

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer
      file_cache_path: '/var/chef/cache/'

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[java::default]
      - recipe[chamber-logmanager::default]
    attributes:
      java:
        jdk_version: '7'
      elasticsearch:
        version: '1.4.0.beta1'
      logstash:
        instance:
          server:
            xms: '256M'
            xmx: '256M'
#            config_templates:
#              input_syslog: 'config/input_syslog.conf.erb'
#              output_stdout: 'config/output_stdout.conf.erb'
#              output_elasticsearch: 'config/output_elasticsearch.conf.erb'
#            pattern_templates:
#              default: 'patterns/custom_patterns.erb'
            elasticsearch_ip: '127.0.0.1'
            enable_embedded_es: false
#      kibana:
#        version: '4.0.0-BETA1.1' # must match version number of above
#        checksum: '0010e467d598b67ba442c2edc5c6df196e8734f826044a58e0da3490a1bb587a' # sha256 ( shasum -a 256 FILENAME )
