---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  vagrantfile_erb: .kitchen.Vagrantfile.erb
  plugins:
    cachier:
      cache:
        scope: ":box"
        auto_detect: false
        enable:
          - yum
        generic_buckets:
          - ['chef', '/var/chef/cache']
  network:
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 9200, host: 9200}]
  customize:
    memory: 512

provisioner:
  name: chef_solo
  solo_rb:
      ssl_verify_mode: verify_peer
      file_cache_path: '/var/chef/cache/'

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[java::default]
      - recipe[chamber-logmanager::default]
    attributes:
      java:
        jdk_version: '7'
      nginx:
        repo_source: 'nginx'
        default_site_enabled: false
        source:
          modules:
            - nginx::http_stub_status_module
      elasticsearch:
        version: '1.3.2'
      logstash:
        instance:
          server:
            xms: '256M'
            xmx: '256M'
#            config_templates:
#              input_syslog: 'config/input_syslog.conf.erb'
#              output_stdout: 'config/output_stdout.conf.erb'
#              output_elasticsearch: 'config/output_elasticsearch.conf.erb'
#            pattern_templates:
#              default: 'patterns/custom_patterns.erb'
            elasticsearch_ip: '127.0.0.1'
            enable_embedded_es: false
